[package]
name = "qwitlib"
version = "0.1.2"
edition = "2021"
authors = ["Silen Locatelli"]
description = "A library for dsv files"
readme = "README.md"
repository = "https://github.com/Qwitqwit/qwitlib"
license = "MIT"

[dependencies]


[dev-dependencies]
tempfile = "3"
