[package]
name = "qwitlib"
version = "0.2.4"
edition = "2021"
authors = ["Silen Locatelli"]
description = "A library for dsv files"
readme = "README.md"
repository = "https://github.com/Qwitqwit/qwitlib"
license = "MIT"

[dependencies]
time = "0.3"
chrono = "0.4"

[dev-dependencies]
tempfile = "3"
